export const API_ENDPOINT = {
  ROOKIE: '/explore/member',
  ROOKIE_DETAIL: '/explore/member',
  PROJECT: '/explore/board',
  BOARD_FILTER: '/explore/boards/filter',

  ROOKIE_SIGNUP: '/rookie/signup',
  ROOKIE_LOGIN: '/rookie/login',
  ROOKIE_REFRESH: '/rookie/refresh',
  CHEERUP: '/api/supports/user',
  LIBRARY_SAVED: '/library/bookmark',
  LIBRARY_MY_PROJECT: '/library/myproject',
  LIBRARY_MY_DETAIL: '/library/myDetail',
  LIBRARY_DELETE_MY_PROJECT: '/library/deleteMyProject',
  LIBRARY_MODIFY_PROJECT_ACTIVE: '/library/modifyProjectActive',
  CHAT_ROOMS: '/api/chat/rooms/my',
  CHAT_ROOM_MESSAGES: '/api/chat/rooms',
  CHAT_SEND: '/api/chat/send',
  CHAT_SEND_TO_ROOM: '/api/chat/rooms',
  WS_CHAT: '/ws-chat',
  BOOKMARK: '/api/bookmark',

  // 게시판 관련 엔드포인트
  BOARDS: '/api/boards',
  BOARD_DETAIL: '/api/boards',
  BOARD_WITH_IMAGES: '/api/boards/with-images',
  BOARD_IMAGES_UPLOAD: '/api/boards/images/upload',
  BOARD_IMAGES_UPLOAD_SINGLE: '/api/boards/images/upload/single',
  BOARD_IMAGES_PREVIEW: '/api/boards/images/preview',
  BOARD_IMAGES_DELETE: '/api/boards/images',
};
