export const ROUTES = {
  intro: '/intro',
  onboarding: '/onboarding',
  home: '/home',
  explore: '/explore',
  rookieDetail: '/explore/rookie/:id',
  chat: '/chat',
  library: '/library',
  hot: '/hot',
  createProject: '/create-project',
  createRookie: '/create-rookie',
  postDetail: '/post/:id',
  toolkit: '/toolkit',
  toolkitDetail: '/toolkit/:id',
  login: '/login',
  //signup: '/signup',
};
