export const ROUTES = {
  intro: '/intro',
  onboarding: '/onboarding',
  home: '/home',
  explore: '/explore',
  rookieDetail: '/explore/rookie/:id',
  chat: '/chat',
  chatRoom: '/chat/:id',
  library: '/library',
  hot: '/hot',
  createProject: '/create-project',
  createRookie: '/create-rookie',
  postDetail: '/post/:id',
  toolkit: '/toolkit',
  signup: '/signup',
  toolkitDetail: '/toolkit/:id',
  login: '/login',
  myprofile: '/myprofile',
  myprofileSetting: '/myprofile/setting',
  search: '/search',
};
